const NEW_MESSAGE = "NEW_MESSAGE";
const MESSAGES_COUNT = "MESSAGES_COUNT";
const ALL_MESSAGES = "ALL_MESSAGES";
const ALL_GAMES = "ALL_GAMES";
const GAME_UPDATED = "GAME_UPDATED";
const DUPLICATED_WORDS = "DUPLICATED_WORDS";
const NO_DUPLICATIONS = "NO_DUPLICATIONS";
const DELETE_GAME_IN_LOBBY = "DELETE_GAME_IN_LOBBY";
const UPDATED_GAME_IN_LOBBY = "UPDATED_GAME_IN_LOBBY";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";

module.exports = {
  NEW_MESSAGE,
  MESSAGES_COUNT,
  ALL_MESSAGES,
  ALL_GAMES,
  GAME_UPDATED,
  DUPLICATED_WORDS,
  NO_DUPLICATIONS,
  DELETE_GAME_IN_LOBBY,
  UPDATED_GAME_IN_LOBBY,
  LOGIN_SUCCESS,
  PUSH_NOTIFICATION,
};
